### ISSUE TITLE
Handle socket.timeout exception in DownloadHelper

### ISSUE THREAD

**Issue by nforro** [rebase-helper/rebase-helper#228]
It seems that `urllib.request.urlopen` sometimes raises `socket.timeout` instead of `urllib.error.URLError`:

```
Traceback (most recent call last):
  File "/home/nforro/devel/rebase-helper/rebasehelper/cli.py", line 231, in run
    app = Application(cli, execution_dir, debug_log_file, report_log_file)
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 91, in __init__
    self._prepare_spec_objects()
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 185, in _prepare_spec_objects
    self.rebase_spec_file.set_version(version)
  File "/home/nforro/devel/rebase-helper/rebasehelper/specfile.py", line 826, in set_version
    self.save()
  File "/home/nforro/devel/rebase-helper/rebasehelper/specfile.py", line 977, in save
    self._update_data()
  File "/home/nforro/devel/rebase-helper/rebasehelper/specfile.py", line 159, in _update_data
    self.sources, self.tar_sources = self._get_initial_sources_list()
  File "/home/nforro/devel/rebase-helper/rebasehelper/specfile.py", line 190, in _get_initial_sources_list
    DownloadHelper.download_file(src[0], abs_path)
  File "/home/nforro/devel/rebase-helper/rebasehelper/utils.py", line 254, in download_file
    response = urllib.request.urlopen(url, timeout=timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1230, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1203, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```

**Comment by nforro** [comment]
Related to #370.
