### ISSUE TITLE
commit_log TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by xenithorb** [rebase-helper/rebase-helper#290]
OS: Fedora 26
Version: rebase-helper-0.9.0-2.fc26.noarch
Tar of `rebase-helper-*`: [rebase-helper-debug-items.tar.gz](https://github.com/rebase-helper/rebase-helper/files/1187943/rebase-helper-debug-items.tar.gz)
Exact command used: `rebase-helper 0.25.1` - I am also definitely inside of a dist-git repository 

```
2017-07-31 10:58:08,649 DEBUG   application.py:86 __init__: Rebase-helper version: 0.9.0
2017-07-31 10:58:08,651 DEBUG   specfile.py:175 _update_data: Updating the extra version
2017-07-31 10:58:08,652 DEBUG   specfile.py:718 extract_version_from_archive_name: Extracting version from 'btrbk-0.25.0.tar.xz' using '%{name}-%{version}.tar.xz'
2017-07-31 10:58:08,652 DEBUG   specfile.py:729 extract_version_from_archive_name: Extracting version using regex 'btrbk-([.0-9]+[-_]?\w*).tar.xz'
2017-07-31 10:58:08,652 DEBUG   specfile.py:734 extract_version_from_archive_name: Extracted version '0.25.0'
2017-07-31 10:58:08,652 DEBUG   specfile.py:686 split_version_string: Splitting string '0.25.0'
2017-07-31 10:58:08,653 DEBUG   specfile.py:695 split_version_string: Divided version '0.25.0' and extra string '' separated by ''
2017-07-31 10:58:09,001 INFO    utils.py:294 download_file: Downloading file from URL https://src.fedoraproject.org/repo/pkgs/btrbk/btrbk-0.25.0.tar.xz/sha512/77a10fdf070129264cc62b2ff643ea4f28c1a4ecab7c026e697ba3b0e01be35674c038762669775f13e3848031ccc6b0e2ed9baef4aedf31ab7d66fdb31c1836/btrbk-0.25.0.tar.xz
2017-07-31 10:58:09,143 DEBUG   specfile.py:175 _update_data: Updating the extra version
2017-07-31 10:58:09,144 DEBUG   specfile.py:718 extract_version_from_archive_name: Extracting version from 'btrbk-0.25.0.tar.xz' using '%{name}-%{version}.tar.xz'
2017-07-31 10:58:09,144 DEBUG   specfile.py:729 extract_version_from_archive_name: Extracting version using regex 'btrbk-([.0-9]+[-_]?\w*).tar.xz'
2017-07-31 10:58:09,144 DEBUG   specfile.py:734 extract_version_from_archive_name: Extracted version '0.25.0'
2017-07-31 10:58:09,144 DEBUG   specfile.py:686 split_version_string: Splitting string '0.25.0'
2017-07-31 10:58:09,144 DEBUG   specfile.py:695 split_version_string: Divided version '0.25.0' and extra string '' separated by ''
2017-07-31 10:58:09,148 DEBUG   application.py:183 _prepare_spec_objects: argument passed as a new source is a version
2017-07-31 10:58:09,148 DEBUG   specfile.py:686 split_version_string: Splitting string '0.25.1'
2017-07-31 10:58:09,148 DEBUG   specfile.py:695 split_version_string: Divided version '0.25.1' and extra string '' separated by ''
2017-07-31 10:58:09,148 DEBUG   specfile.py:661 set_version: Updating version in SPEC from '0.25.0' with '0.25.1'
2017-07-31 10:58:09,150 DEBUG   specfile.py:869 _write_spec_file_to_disc: Writing SPEC file '/home/xenith/fedora-scm/btrbk/rebase-helper-results/btrbk.spec' to the disc
2017-07-31 10:58:09,151 DEBUG   specfile.py:175 _update_data: Updating the extra version
2017-07-31 10:58:09,151 DEBUG   specfile.py:718 extract_version_from_archive_name: Extracting version from 'btrbk-0.25.1.tar.xz' using '%{name}-%{version}.tar.xz'
2017-07-31 10:58:09,151 DEBUG   specfile.py:729 extract_version_from_archive_name: Extracting version using regex 'btrbk-([.0-9]+[-_]?\w*).tar.xz'
2017-07-31 10:58:09,151 DEBUG   specfile.py:734 extract_version_from_archive_name: Extracted version '0.25.1'
2017-07-31 10:58:09,151 DEBUG   specfile.py:686 split_version_string: Splitting string '0.25.1'
2017-07-31 10:58:09,151 DEBUG   specfile.py:695 split_version_string: Divided version '0.25.1' and extra string '' separated by ''
2017-07-31 10:58:09,156 DEBUG   specfile.py:151 download_remote_sources: File '/home/xenith/fedora-scm/btrbk/btrbk-0.25.1.tar.xz' doesn't exist locally, downloading it.
2017-07-31 10:58:09,970 INFO    utils.py:294 download_file: Downloading file from URL https://digint.ch/download/btrbk/releases/btrbk-0.25.1.tar.xz
2017-07-31 10:58:10,129 DEBUG   specfile.py:560 set_extra_version: Updating extra version in SPEC to ''
2017-07-31 10:58:10,130 DEBUG   specfile.py:496 set_release_number: Changing release line to 'Release:        1%{?dist}'
2017-07-31 10:58:10,130 DEBUG   specfile.py:869 _write_spec_file_to_disc: Writing SPEC file '/home/xenith/fedora-scm/btrbk/rebase-helper-results/btrbk.spec' to the disc
2017-07-31 10:58:10,132 DEBUG   specfile.py:175 _update_data: Updating the extra version
2017-07-31 10:58:10,132 DEBUG   specfile.py:718 extract_version_from_archive_name: Extracting version from 'btrbk-0.25.1.tar.xz' using '%{name}-%{version}.tar.xz'
2017-07-31 10:58:10,132 DEBUG   specfile.py:729 extract_version_from_archive_name: Extracting version using regex 'btrbk-([.0-9]+[-_]?\w*).tar.xz'
2017-07-31 10:58:10,132 DEBUG   specfile.py:734 extract_version_from_archive_name: Extracted version '0.25.1'
2017-07-31 10:58:10,132 DEBUG   specfile.py:686 split_version_string: Splitting string '0.25.1'
2017-07-31 10:58:10,132 DEBUG   specfile.py:695 split_version_string: Divided version '0.25.1' and extra string '' separated by ''
2017-07-31 10:58:10,139 DEBUG   specfile.py:869 _write_spec_file_to_disc: Writing SPEC file '/home/xenith/fedora-scm/btrbk/rebase-helper-results/btrbk.spec' to the disc
2017-07-31 10:58:10,141 DEBUG   specfile.py:175 _update_data: Updating the extra version
2017-07-31 10:58:10,141 DEBUG   specfile.py:718 extract_version_from_archive_name: Extracting version from 'btrbk-0.25.1.tar.xz' using '%{name}-%{version}.tar.xz'
2017-07-31 10:58:10,141 DEBUG   specfile.py:729 extract_version_from_archive_name: Extracting version using regex 'btrbk-([.0-9]+[-_]?\w*).tar.xz'
2017-07-31 10:58:10,141 DEBUG   specfile.py:734 extract_version_from_archive_name: Extracted version '0.25.1'
2017-07-31 10:58:10,141 DEBUG   specfile.py:686 split_version_string: Splitting string '0.25.1'
2017-07-31 10:58:10,141 DEBUG   specfile.py:695 split_version_string: Divided version '0.25.1' and extra string '' separated by ''
2017-07-31 10:58:10,147 DEBUG   archive.py:237 extract_archive: Extracting '/home/xenith/fedora-scm/btrbk/btrbk-0.25.0.tar.xz' into '/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources'
2017-07-31 10:58:10,167 DEBUG   archive.py:237 extract_archive: Extracting '/home/xenith/fedora-scm/btrbk/btrbk-0.25.1.tar.xz' into '/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/new_sources'
2017-07-31 10:58:10,186 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'config', '--get', 'merge.tool'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23200>, shell=False
2017-07-31 10:58:10,192 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,192 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'config', '--get', 'user.name'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23200>, shell=False
2017-07-31 10:58:10,198 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,198 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'config', '--get', 'user.email'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23200>, shell=False
2017-07-31 10:58:10,203 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,204 DEBUG   specfile.py:869 _write_spec_file_to_disc: Writing SPEC file '/home/xenith/fedora-scm/btrbk/rebase-helper-results/btrbk.spec' to the disc
2017-07-31 10:58:10,205 DEBUG   specfile.py:175 _update_data: Updating the extra version
2017-07-31 10:58:10,205 DEBUG   specfile.py:718 extract_version_from_archive_name: Extracting version from 'btrbk-0.25.1.tar.xz' using '%{name}-%{version}.tar.xz'
2017-07-31 10:58:10,205 DEBUG   specfile.py:729 extract_version_from_archive_name: Extracting version using regex 'btrbk-([.0-9]+[-_]?\w*).tar.xz'
2017-07-31 10:58:10,205 DEBUG   specfile.py:734 extract_version_from_archive_name: Extracted version '0.25.1'
2017-07-31 10:58:10,205 DEBUG   specfile.py:686 split_version_string: Splitting string '0.25.1'
2017-07-31 10:58:10,206 DEBUG   specfile.py:695 split_version_string: Divided version '0.25.1' and extra string '' separated by ''
2017-07-31 10:58:10,210 DEBUG   patch_helper.py:370 patch: Patching source by patch tool git
2017-07-31 10:58:10,210 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'init', '/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23bd8>, shell=False
2017-07-31 10:58:10,217 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,217 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'add', '.'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23bd8>, shell=False
2017-07-31 10:58:10,239 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,239 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'commit', '-m', 'Initial Commit'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23bd8>, shell=False
2017-07-31 10:58:10,249 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 1
2017-07-31 10:58:10,249 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'init', '/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/new_sources/btrbk-0.25.1'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/new_sources/btrbk-0.25.1, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23bd8>, shell=False
2017-07-31 10:58:10,255 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,256 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'add', '.'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/new_sources/btrbk-0.25.1, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23bd8>, shell=False
2017-07-31 10:58:10,277 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,278 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'commit', '-m', 'Initial Commit'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/new_sources/btrbk-0.25.1, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23bd8>, shell=False
2017-07-31 10:58:10,287 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 1
2017-07-31 10:58:10,288 DEBUG   patch_helper.py:257 create_prep_script: Extract prep script
2017-07-31 10:58:10,288 DEBUG   patch_helper.py:260 create_prep_script: prep section '['', '', '', '', '', '', '']'
2017-07-31 10:58:10,288 DEBUG   patch_helper.py:268 create_prep_script: Fix %SOURCES tags in prep script
2017-07-31 10:58:10,288 DEBUG   patch_helper.py:270 create_prep_script: Fix %PATCH tags in prep script
2017-07-31 10:58:10,288 DEBUG   patch_helper.py:273 create_prep_script: Writing Prep script '/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/prep_script' to the disc
2017-07-31 10:58:10,289 INFO    patch_helper.py:148 _git_rebase: Git-rebase operation to btrbk-0.25.1 is ongoing...
2017-07-31 10:58:10,289 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'remote', 'add', 'new_upstream', '/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/new_sources/btrbk-0.25.1'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23248>, shell=False
2017-07-31 10:58:10,294 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,295 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'fetch', 'new_upstream'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23248>, shell=False
2017-07-31 10:58:10,304 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 0
2017-07-31 10:58:10,304 DEBUG   utils.py:389 run_subprocess_cwd_env: cmd=['git', '-c', 'user.name=rebase-helper', '-c', 'user.email=rebase-helper@localhost.local', 'log', '--pretty=oneline'], cwd=/home/xenith/fedora-scm/btrbk/rebase-helper-workspace/old_sources/btrbk-0.25.0, env=None, input=None, output=<StringIO.StringIO instance at 0x7f75e5b23248>, shell=False
2017-07-31 10:58:10,310 DEBUG   utils.py:475 run_subprocess_cwd_env: subprocess exited with return code 128
2017-07-31 10:58:10,310 DEBUG   patch_helper.py:115 _prepare_git: Outputdata from git log None
2017-07-31 10:58:10,311 ERROR   cli.py:251 run: 
rebase-helper failed due to an unexpected error. Please report this problem
using the following link: https://github.com/rebase-helper/rebase-helper/issues/new
and include the content of
'/home/xenith/fedora-scm/btrbk/rebase-helper-results/rebase-helper-debug.log'
file in the report.
Thank you!
2017-07-31 10:58:10,311 DEBUG   cli.py:258 run:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rebasehelper/cli.py", line 232, in run
    app.run()
  File "/usr/lib/python2.7/site-packages/rebasehelper/application.py", line 716, in run
    self.patch_sources(sources)
  File "/usr/lib/python2.7/site-packages/rebasehelper/application.py", line 403, in patch_sources
    **self.kwargs)
  File "/usr/lib/python2.7/site-packages/rebasehelper/patch_helper.py", line 371, in patch
    return self._tool.run_patch(old_dir, new_dir, rest_sources, git_helper, patches, prep, **kwargs)
  File "/usr/lib/python2.7/site-packages/rebasehelper/patch_helper.py", line 331, in run_patch
    return cls._git_rebase()
  File "/usr/lib/python2.7/site-packages/rebasehelper/patch_helper.py", line 150, in _git_rebase
    init_hash, last_hash = cls._prepare_git(upstream)
  File "/usr/lib/python2.7/site-packages/rebasehelper/patch_helper.py", line 119, in _prepare_git
    last_hash = GitHelper.get_commit_hash_log(cls.output_data, number=number)
  File "/usr/lib/python2.7/site-packages/rebasehelper/utils.py", line 792, in get_commit_hash_log
    commit = commit_log[number]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by nforro** [comment]
Thanks for the reporting this.
The problem is caused by custom `pre-commit` hook. We need to run `git commit` with `--no-verify` option  to prevent it from executing.

**Comment by xenithorb** [comment]
Nice catch! Sorry for the edge case. I do have a pre-commit hook to check that I've set the email at the repo level and _not_ the global email. (I work on many projects with many different emails, so this is a safety precaution against appearing as a different email in commit messages)
