### ISSUE TITLE
Detecting new version's build failure

### ISSUE THREAD

**Issue by junaruga** [rebase-helper/rebase-helper#375]
This issue is for `rubygem-childprocess` package.

```
(venv) $ pwd
/home/jaruga/fed/rubygem-childprocess

(venv) $ rebase-helper 
Results directory 'rebase-helper-results' exists, removing it
Workspace directory 'rebase-helper-workspace' exists, removing it
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
Running 'rubygems' versioneer
Determined latest upstream version '0.8.0'
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
Running 'Ruby Helper' spec hook
Downloading file from URL https://src.fedoraproject.org/repo/pkgs/rubygem-childprocess/childprocess-0.5.9.gem/sha512/5a671e59d19531347438dc149d5309218c7e439cfd0bfcfe201ae8e1099a2608a0170f9a3f3752fb709afc6b68fa3a10dc60d0632af545a9ba71483c7be2c21d/childprocess-0.5.9.gem
100%[=============================>]    28.50K  eta 00:00:00 
Downloading file from URL http://rubygems.org/gems/childprocess-0.8.0.gem
100%[=============================>]    32.00K  eta 00:00:00 
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
git-rebase operation to childprocess-0.8.0 is ongoing...
Building packages for rubygem-childprocess version 0.5.9
Building SRPM
Building SRPM finished successfully
Building RPMs
Building RPMs finished successfully
Building packages for rubygem-childprocess version 0.8.0
Building SRPM
Building SRPM finished successfully
Building RPMs
Building binary packages failed.
Not known issue
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
Do you want rebase-helper to try to build the packages one more time [Y/n]? Y
Building SRPM
Building SRPM finished successfully
Building RPMs
Building binary packages failed.
Removed files packaged in SPEC file:
/var/tmp/rpm-tmp.jQ8p9r (%check)
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
Do you want rebase-helper to try to build the packages one more time [Y/n]? Y
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
warning: bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
Running 'text' output tool.

Available logs:
Debug log:
/home/jaruga/git/fedora-packages/rubygem-childprocess/rebase-helper-results/rebase-helper-debug.log
Old build logs and (S)RPMs:
/home/jaruga/git/fedora-packages/rubygem-childprocess/rebase-helper-results/old-build
New build logs and (S)RPMs:
/home/jaruga/git/fedora-packages/rubygem-childprocess/rebase-helper-results/new-build

Rebased sources:
/home/jaruga/git/fedora-packages/rubygem-childprocess/rebase-helper-results/rebased-sources
Generated patch:
/home/jaruga/git/fedora-packages/rubygem-childprocess/rebase-helper-results/changes.patch

text report:
/home/jaruga/git/fedora-packages/rubygem-childprocess/rebase-helper-results/report.txt

Building package failed with unknown reason. Check all available log files.
```

The actual reason of the failure is

/home/jaruga/git/fedora-packages/rubygem-childprocess/rebase-helper-results/new-build/RPM/build.log

```
...
+ rspec spec
.F...............F................................................
Failures:
  1) ChildProcess validates cleanly
     Failure/Error: let(:gemspec) { eval(File.read "#{here}/../childprocess.gemspec") }
     Errno::ENOENT:
       No such file or directory - git 
     # ./spec/childprocess_spec.rb:11:in `eval'
     # (eval):18:in `block (3 levels) in <top (required)>'
     # /usr/share/rubygems/rubygems/specification.rb:2055:in `initialize'
     # (eval):5:in `new'
     # (eval):5:in `block (2 levels) in <top (required)>'
     # ./spec/childprocess_spec.rb:11:in `eval'
     # ./spec/childprocess_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/childprocess_spec.rb:15:in `block (3 levels) in <top (required)>'
     # /usr/share/rubygems/rubygems/user_interaction.rb:48:in `use_ui'
     # ./spec/childprocess_spec.rb:15:in `block (2 levels) in <top (required)>'
  2) ChildProcess lets a detached child live on
     Failure/Error: expect(alive?(p_pid)).to_not be true
       expected not #<TrueClass:20> => true
                got #<TrueClass:20> => true
       Compared using equal?, which compares object identity.
     # ./spec/childprocess_spec.rb:188:in `block (2 levels) in <top (required)>'
Finished in 2.79 seconds (files took 0.09529 seconds to load)
66 examples, 2 failures
...
error: Bad exit status from /var/tmp/rpm-tmp.jQ8p9r (%check)
    bogus date in %changelog: Tue Sep 23 2013 Mo Morsi <mmorsi@redhat.com> - 0.3.9-1
    Bad exit status from /var/tmp/rpm-tmp.jQ8p9r (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.5/site-packages/mockbuild/util.py", line 598, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)mockbuild.exception.Error: Command failed:-
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/rubygem-childprocess.spec 
```

I want `rebase-helper` to detect the reason is the build failure for the new version. And the reason is in `build.log`.

Possible?

**Comment by nforro** [comment]
This is being worked on in #341. mock exit code will be used to determine which of the log files contains the failure.

**Comment by junaruga** [comment]
That's great news.
Please keep this issue open until the #341 will be fixed.
