### ISSUE TITLE
Modify rebase helper output

### ISSUE THREAD

**Issue by skisela** [rebase-helper/rebase-helper#376]
```
$ rebase-helper --buildtool koji
...
...
rebase-helper failed due to an unexpected error. Please report this problem
'/home/skisela/fedora/rubygem-coffee-script-source/rebase-helper-results/rebase-helper-debug.log'
file in the report.
Thank you!
```
Maybe better wording would be to advise the user to check the debug log first and then create an issue if still desperate? Here the reason of the fail is quite obvious.

#### rebase-helper-results/rebase-helper-debug.log:
```
2017-11-01 09:40:30,950 DEBUG cli.py:293 run: 
Traceback (most recent call last):
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/rebasehelper/cli.py", line 267, in run
    app.run()
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/rebasehelper/application.py", line 805, in run
    build = self.build_packages()
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/rebasehelper/application.py", line 532, in build_packages
    build_dict.update(builder.build(spec, sources, patches, results_dir, **build_dict))
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/rebasehelper/build_helper.py", line 379, in build
    return self._tool.build(*args, **kwargs)
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/rebasehelper/build_tools/koji_tool.py", line 165, in build
    rpms, rpm_logs, koji_task_id = cls._scratch_build(srpm, **kwargs)
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/rebasehelper/build_tools/koji_tool.py", line 82, in _scratch_build
    session = cls.koji_helper.session_maker()
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/rebasehelper/utils.py", line 870, in session_maker
    koji_session.ssl_login(cls.cert, cls.ca_cert, cls.ca_cert)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2273, in ssl_login
    sinfo = self.callMethod('sslLogin', proxyuser)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2321, in callMethod
    return self._callMethod(name, args, opts)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2439, in _callMethod
    return self._sendCall(handler, headers, request)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2352, in _sendCall
    return self._sendOneCall(handler, headers, request)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2397, in _sendOneCall
    r = self.rsession.post(handler, **callopts)
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/skisela/packages/venv-rebase-helper/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='koji.fedoraproject.org', port=443): Max retries exceeded with url: /kojihub/ssllogin (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

**Comment by nforro** [comment]
It doesn't really matter if an user is experienced enough to be able to deduce something from debug log or not, the point is the issue should be reported and fixed - in this case the `SSLError` exception should be catched and handled properly.
