### ISSUE TITLE
Handle LZMAError and ReadError while opening archive

### ISSUE THREAD

**Issue by nforro** [rebase-helper/rebase-helper#383]
Reproducer: javapackages-tools 4.7.0 -> 5.0.0

```python
Traceback (most recent call last):
  File "/home/nforro/devel/rebase-helper/rebasehelper/cli.py", line 279, in run
    app.run()
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 755, in run
    sources = self.prepare_sources()
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 391, in prepare_sources
    new_dir = Application.extract_sources(self.new_sources, new_sources_dir)
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 365, in extract_sources
    Application.extract_archive(archive_path, destination)
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 356, in extract_archive
    archive.extract_archive(destination)
  File "/home/nforro/devel/rebase-helper/rebasehelper/archive.py", line 239, in extract_archive
    archive = self._archive_type.open(self._filename)
  File "/home/nforro/devel/rebase-helper/rebasehelper/archive.py", line 92, in open
    return tarfile.open(mode='r', fileobj=xz_file)
  File "/usr/lib64/python3.6/tarfile.py", line 1568, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1640, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1616, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1479, in __init__
    self.firstmember = self.next()
  File "/usr/lib64/python3.6/tarfile.py", line 2294, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python3.6/tarfile.py", line 1089, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib64/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib64/python3.6/gzip.py", line 406, in _read_gzip_header
    magic = self._fp.read(2)
  File "/usr/lib64/python3.6/gzip.py", line 91, in read
    self.file.read(size-self._length+read)
  File "/usr/lib64/python3.6/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/usr/lib64/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib64/python3.6/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
_lzma.LZMAError: Input format not supported by decoder
```

**Comment by nforro** [comment]
Reproducer: 915resolution 0.5.2 -> 0.5.3

```python
Traceback (most recent call last):
  File "/home/nforro/devel/rebase-helper/rebasehelper/cli.py", line 279, in run
    app.run()
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 755, in run
    sources = self.prepare_sources()
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 391, in prepare_sources
    new_dir = Application.extract_sources(self.new_sources, new_sources_dir)
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 365, in extract_sources
    Application.extract_archive(archive_path, destination)
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 356, in extract_archive
    archive.extract_archive(destination)
  File "/home/nforro/devel/rebase-helper/rebasehelper/archive.py", line 239, in extract_archive
    archive = self._archive_type.open(self._filename)
  File "/home/nforro/devel/rebase-helper/rebasehelper/archive.py", line 151, in open
    return tarfile.TarFile.open(filename)
  File "/usr/lib64/python3.6/tarfile.py", line 1573, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```
