### ISSUE TITLE
Rebase fails on expanding %autosetup

### ISSUE THREAD

**Issue by skisela** [rebase-helper/rebase-helper#394]
Rebasing `python-yattag` fails on expanding this line
```
%autosetup -n %{pkgname}-%{version}
```
Traceback:
```
    2017-11-29 16:00:44,878 DEBUG   cli.py:293 run:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/rebasehelper/cli.py", line 267, in run
        app.run()
      File "/usr/lib/python3.6/site-packages/rebasehelper/application.py", line 783, in run
        sources = self.prepare_sources()
      File "/usr/lib/python3.6/site-packages/rebasehelper/application.py", line 389, in prepare_sources
        dirname = self.spec_file.get_setup_dirname()
      File "/usr/lib/python3.6/site-packages/rebasehelper/specfile.py", line 1346, in get_setup_dirname
        line = rpm.expandMacro(line)
    _rpm.error: error expanding macro
```

**Comment by nforro** [comment]
Can't reproduce on F26 with latest master. I can se only:
```
error: lua script failed: attempt to index a nil value
```
but that doesn't prevent the rebase from succeeding, and I'm not sure it's even related.

**Comment by nforro** [comment]
OK, reproduced on F27 with `rpm-4.14.0-2.fc27`.
