### ISSUE TITLE
another spec which can't be parsed by rpm

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#608]
Spec: https://github.com/packit-service/systemd-source-git/blob/bd6ab9d04aa65ab258cbb8f7d09b11da89cf23db/fedora/systemd.spec

Is this a dupe of https://github.com/packit-service/packit/issues/201?

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rebasehelper/specfile.py", line 270, in _update_data
    self.spc = RpmHelper.parse_spec(self.path, flags=rpm.RPMSPEC_ANYARCH)
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/rpm_helper.py", line 176, in parse_spec
    result = rpm.spec(tmp.name, flags) if flags is not None else rpm.spec(tmp.name)
ValueError: can't parse specfile


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rebasehelper/specfile.py", line 274, in _update_data
    self.spc = RpmHelper.parse_spec(self.path)
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/rpm_helper.py", line 176, in parse_spec
    result = rpm.spec(tmp.name, flags) if flags is not None else rpm.spec(tmp.name)
ValueError: can't parse specfile


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tt/g/user-cont/packit/packit/cli/utils.py", line 57, in covered_func
    func(config=config, *args, **kwargs)
  File "/home/tt/g/user-cont/packit/packit/cli/srpm.py", line 62, in srpm
    srpm_path = api.create_srpm(output_file=output)
  File "/home/tt/g/user-cont/packit/packit/api.py", line 353, in create_srpm
    spec_version = self.up.get_specfile_version()
  File "/home/tt/g/user-cont/packit/packit/upstream.py", line 326, in get_specfile_version
    version = self.specfile.get_version()
  File "/home/tt/g/user-cont/packit/packit/upstream.py", line 110, in specfile
    changelog_entry=None,
  File "/usr/lib/python3.7/site-packages/rebasehelper/specfile.py", line 210, in __init__
    self._update_data()
  File "/usr/lib/python3.7/site-packages/rebasehelper/specfile.py", line 276, in _update_data
    raise RebaseHelperError("Problem with parsing SPEC file '%s'" % self.path)
rebasehelper.exceptions.RebaseHelperError
```

**Comment by nforro** [comment]
This is a different issue, however I'm not sure what's the cause, rpm doesn't output anything at all in this case.

**Comment by nforro** [comment]
Sorry, my mistake. As it turns out, I'm not able to reproduce the issue, the spec file can be parsed just fine.

However, I fixed a bug that prevented rpm output from being logged, and included it in the exception message for convenience (see PR #609). Hopefully that will make finding the cause of these issues easier.

**Comment by TomasTomecek** [comment]
Cool! Will try that PR out to investigate this issue.

**Comment by TomasTomecek** [comment]
You're correct, the error was that a file could not be found. Thanks!
