### ISSUE TITLE
parsing a spec file requires the archive to be present locally

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#710]
```
Traceback (most recent call last):                                                    
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/rpm_helper.py", line 183, in parse_spec                                                                        
    result = rpm.spec(tmp.name, flags) if flags is not None else rpm.spec(tmp.name)                                                                                          
ValueError: can't parse specfile                                                                                                                                             
During handling of the above exception, another exception occurred:                                                                                                          
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/rpm_helper.py", line 194, in get_rpm_spec                                                                     
    spec = cls.parse_spec(path, flags=rpm.RPMSPEC_ANYARCH)
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/rpm_helper.py", line 188, in parse_spec
    raise RebaseHelperError('Failed to parse SPEC file{0}'.format(': ' + str(output) if output else ''))
rebasehelper.exceptions.RebaseHelperError: Failed to parse SPEC file: error: Bad source: /home/packit/rpmbuild/SOURCES/systemd-63ea803.tar.gz: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/rpm_helper.py", line 183, in parse_spec
    result = rpm.spec(tmp.name, flags) if flags is not None else rpm.spec(tmp.name)
ValueError: can't parse specfile
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/packit/base_git.py", line 95, in specfile
    sources_location=str(self.absolute_specfile_dir),
  File "/usr/lib/python3.7/site-packages/rebasehelper/specfile.py", line 266, in __init__
    self.spc: rpm.spec = RpmHelper.get_rpm_spec(self.path)
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/rpm_helper.py", line 197, in get_rpm_spec
    spec = cls.parse_spec(path)
  File "/usr/lib/python3.7/site-packages/rebasehelper/helpers/rpm_helper.py", line 188, in parse_spec
    raise RebaseHelperError('Failed to parse SPEC file{0}'.format(': ' + str(output) if output else ''))
rebasehelper.exceptions.RebaseHelperError: Failed to parse SPEC file: error: Unable to open /home/packit/rpmbuild/SOURCES/triggers.systemd: No such file or directory
```
What I don't understand is:

* there are actually 2 tracebacks here
* the path in the traceback, `rpmbuild/SOURCES/`, is not correct, we are passing different path to SpecFile constructor: `SpecFile(path=path_to_spec, sources_dir=dir_of_the_spec)`

it's true that the archive is not present in the dir, yet - it's generated after the spec is parsed; but for the triggers.systemd file, it's in the dir, but I don't understand why the path says rpmbuild/SOURCES, seems like sources_dir is not utilized

Source: https://github.com/packit-service/packit-service/issues/138

**Comment by FrNecas** [comment]
Thanks for reporting the issue!

The reason for 2 tracebacks seems quite simple, `RpmHelper.get_rpm_spec()` tries to parse the spec twice - one without the RPMSPEC_FORCE flag and in case of failure with the flag and that should succeed (which in your case doesn't).

It doesn't seem to be a problem on our end - rpmspec doesn't seem to parse the spec either

```
$ rpmspec -P systemd.spec
error: Unable to open /home/fnecas/rpmbuild/SOURCES/triggers.systemd: No such file or directory
```

Apparently the `rpmbuild/SOURCES` path doesn't come from rebase-helper but rather from the spec file. After some testing, I found this line to be problematic for parsing: https://github.com/packit-service/systemd-rhel8-flock/blob/master/packaging/rpm/systemd.spec#L459 . When removed, the spec file parsing doesn't fail.

**Comment by TomasTomecek** [comment]
Oh wow, thank you for such a detailed analysis! Glad you found the root cause.

But I still feel like the behaviour is incorrect:
```python
In [1]: from rebasehelper.specfile import SpecFile                                                                                                                           
                                                                                      
In [2]: s = SpecFile(path="packaging/rpm/systemd.spec", sources_location="packaging/rpm/")   
...
RebaseHelperError: Failed to parse SPEC file: error: Unable to open /home/tt/rpmbuild/SOURCES/triggers.systemd: No such file or directory
```
It should not look inside `~/rpmbuild/SOURCES` but instead it should check `packaging/rpm/`.

**Comment by TomasTomecek** [comment]
finally figured it out: the problem is that you parse spec twice, first time w/o custom _srcdir; see PR above
