### ISSUE TITLE
Unhandled exception in LookasideCacheHelper

### ISSUE THREAD

**Issue by nforro** [rebase-helper/rebase-helper#794]
```
Traceback (most recent call last):
  File "/home/nforro/devel/rebase-helper/rebasehelper/cli.py", line 178, in run
    app = Application(config, start_dir, execution_dir, results_dir)
  File "/home/nforro/devel/rebase-helper/rebasehelper/application.py", line 114, in __init__
    uploaded = LookasideCacheHelper.update_sources('fedpkg', self.rebased_sources_dir,
  File "/home/nforro/devel/rebase-helper/rebasehelper/helpers/lookaside_cache_helper.py", line 208, in update_sources
    cls._upload_source(url, package, source_dir, filename, hashtype, hsh)
  File "/home/nforro/devel/rebase-helper/rebasehelper/helpers/lookaside_cache_helper.py", line 174, in _upload_source
    state = post(check_only=True)
  File "/home/nforro/devel/rebase-helper/rebasehelper/helpers/lookaside_cache_helper.py", line 168, in post
    r = requests.post(url, data=cd, headers=cd.headers, auth=auth)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests_gssapi/gssapi_.py", line 279, in handle_response
    _r = self.handle_401(response, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests_gssapi/gssapi_.py", line 192, in handle_401
    _r = self.authenticate_user(response, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests_gssapi/gssapi_.py", line 181, in authenticate_user
    _r = response.connection.send(response.request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: Remote end closed connection without response
```

**Comment by nforro** [comment]
This should be fixed by #820.
