### ISSUE TITLE
specfile.set_version(version, preserve_macros=True) recurses infinitely when "Version" has no numbers

### ISSUE THREAD

**Issue by TomasTomecek** [rebase-helper/rebase-helper#855]
```
  File "/home/tt/g/user-cont/packit/packit/base_git.py", line 367, in set_specfile_content                                                                                                    
    self.specfile.set_version(this_version)                                                                                                                                                   
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 535, in set_version                                                                                            
    self.set_tag('Version', version, preserve_macros=preserve_macros)                                                                                                                         
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 108, in wrapper                                                                                                
    func(spec, *args, **kwargs)                                                                                                                                                               
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 846, in set_tag                                                                                                
    value = _process_value(self.get_raw_tag_value(tag) or '', value)                                                                                                                          
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 754, in _process_value                                                                                         
    value, _ = _expand_macros(curval)                                                                                                                                                         
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 643, in _expand_macros                                                                                         
    rep, new_macros = _expand_macros(value)
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 643, in _expand_macros
    rep, new_macros = _expand_macros(value)
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 643, in _expand_macros
    rep, new_macros = _expand_macros(value)
  [Previous line repeated 974 more times]
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 638, in _expand_macros
    for macro, span in _find_macros(s):
  File "/home/tt/g/rebase-helper/rebase-helper/rebasehelper/specfile.py", line 617, in _find_macros
    macro_re = re.compile(r'%(?P<brace>{\??)?(?P<name>\w+)(?(brace)})')
```

```
Version: %{general_version}%{?prerel:~%{prerel}}
```

I'm wondering what would be the right thing to do here - that's why I haven't sent a PR with a fix because I'm not sure what to do here.

I guess that `set_version` could raise an exception saying it can't fulfil the request: update Version while preserving macros.

**Comment by nforro** [comment]
I'm not able to reproduce this, could you share the full specfile? And also the value of `this_version`?

**Comment by TomasTomecek** [comment]
whoops, thought it would be easier to reproduce: I filed this issue and disappeared for a vacation :D

Here is a detailed reproducer:
```python
In [1]: import rebasehelper                    
                                               
In [2]: from rebasehelper.specfile import SpecFile                                             
                                                                                               
In [3]: s = SpecFile("./python3.9.spec")       
                                                                                               
In [4]: s.set_version("3.9.10")   
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-4-3c17dd468a12> in <module>
----> 1 s.set_version("3.9.10")
        global s.set_version = <bound method SpecFile.set_version of <rebasehelper.specfile.SpecFile object at 0x7f98ed04a880>>

~/g/rebase-helper/rebase-helper/rebasehelper/specfile.py in set_version(self=<rebasehelper.specfile.SpecFile object>, version='3.9.10', preserve_macros=True)
    533     def set_version(self, version: str, preserve_macros: bool = True) -> None:
    534         logger.verbose('Updating version in SPEC from %s to %s', self.header.version, version)
--> 535         self.set_tag('Version', version, preserve_macros=preserve_macros)
        self.set_tag = <bound method saves.<locals>.wrapper of <rebasehelper.specfile.SpecFile object at 0x7f98ed04a880>>
        version = '3.9.10'
        preserve_macros = True
    536
    537     def set_release(self, release: str, preserve_macros: bool = True) -> None:

~/g/rebase-helper/rebase-helper/rebasehelper/specfile.py in wrapper(spec=<rebasehelper.specfile.SpecFile object>, *args=('Version', '3.9.10'), **kwargs={'preserve_macros': True})
    106     """Decorator for saving the SpecFile after a method is run."""
    107     def wrapper(spec, *args, **kwargs):
--> 108         func(spec, *args, **kwargs)
        global func = undefined
        spec = <rebasehelper.specfile.SpecFile object at 0x7f98ed04a880>
        args = ('Version', '3.9.10')
        kwargs = {'preserve_macros': True}
    109         spec.save()
    110

~/g/rebase-helper/rebase-helper/rebasehelper/specfile.py in set_tag(self=<rebasehelper.specfile.SpecFile object>, tag='Version', value='3.9.10', preserve_macros=True)
    844
    845         if preserve_macros:
--> 846             value = _process_value(self.get_raw_tag_value(tag) or '', value)
        value = '3.9.10'
        _process_value = <function SpecFile.set_tag.<locals>._process_value at 0x7f98ee199c10>
        self.get_raw_tag_value = <bound method SpecFile.get_raw_tag_value of <rebasehelper.specfile.SpecFile object at 0x7f98ed04a880>>
        tag = 'Version'
    847         self.set_raw_tag_value(tag, value)
    848

~/g/rebase-helper/rebase-helper/rebasehelper/specfile.py in _process_value(curval='%{general_version}%{?prerel:~%{prerel}}', newval='3.9.10')
    752             and redefines values of macros accordingly
    753             """
--> 754             value, _ = _expand_macros(curval)
        value = undefined
        _ = undefined
        global _expand_macros = undefined
        curval = '%{general_version}%{?prerel:~%{prerel}}'
    755             _sync_macros(curval + newval)
    756             tokens = _tokenize(value)

~/g/rebase-helper/rebase-helper/rebasehelper/specfile.py in _expand_macros(s='%{general_version}%{?prerel:~%{prerel}}')
    641                     continue
    642                 macros.add(macro)
--> 643                 rep, new_macros = _expand_macros(value)
        rep = undefined
        new_macros = undefined
        global _expand_macros = undefined
        value = '%{pybasever}.5\n#global prerel ...\n%global upstream_version %{general_version}%{?prerel}'
    644                 macros |= new_macros
    645                 if _find_macros(rep):

... last 1 frames repeated, from the frame below ...

~/g/rebase-helper/rebase-helper/rebasehelper/specfile.py in _expand_macros(s='%{pybasever}.5\n#global prerel ...\n%global upstream_version %{general_version}%{?prerel}')
    641                     continue
    642                 macros.add(macro)
--> 643                 rep, new_macros = _expand_macros(value)
        rep = '3.9'
        new_macros = set()
        global _expand_macros = undefined
        value = '%{pybasever}.5\n#global prerel ...\n%global upstream_version %{general_version}%{?prerel}'
    644                 macros |= new_macros
    645                 if _find_macros(rep):

RecursionError: maximum recursion depth exceeded while calling a Python object
```

This is python3.9 from CentOS Stream 9:

https://gitlab.com/redhat/centos-stream/rpms/python3.9/-/blob/24e9be4681d3b590b930e236448d897777f896f9/python3.9.spec

Tried against current git main and still getting the same exc.

**Comment by nforro** [comment]
Just an update, this is definitely a bug, the problem is in this regex that matches more than it should:

https://github.com/rebase-helper/rebase-helper/blob/c6f09d8b98aa9e52935dfd56367b1a618cd57ff9/rebasehelper/specfile.py#L577-L594
